### ISSUE TITLE
Hacktoberfest 2022 💫

### ISSUE THREAD

**Issue by daoodaba975** [GalsenDev221/made.in.senegal#39]
To contribute for Hacktoberfest 2022 edition, you'll just need to add project (if you have a project to add).
No needed any translation or minor fix on this project.
Read our [contributor](https://github.com/GalsenDev221/made.in.senegal/blob/master/CONTRIBUTING.md) guide first !

**Comment by LucianeFernandesRoque** [comment]
can i take this issue?

**Comment by daoodaba975** [comment]
Sorry @LucianeFernandesRoque but this issue is only open for developer who have senegalese project to add.
This repo is listing tools built by Senegalese developers.
